version: '3'
services:
  rabbit:
    image: "rabbitmq:latest"
    networks:
      spring-cloud-overlay:
        aliases:
          - rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_VHOST=/

networks:
  spring-cloud-overlay:
    external:
      name: spring-cloud-overlay
