version: '3'
services:
#  configBus:
#    image: "asd1245dss/cloud-config-bus:latest"
#    networks:
#      spring-cloud-overlay:
#        aliases:
#          - configBus
#    ports:
#      - "8090:8090"
#    depends_on:
#      - "configServer"
#    environment:
#      - EUREKA_SERVER_LIST=http://eurekaServer1:8761/eureka/,http://eurekaServer2:8761/eureka/,http://eurekaServer3:8761/eureka/
#      - CLOUD_CONFIG_SERVER=http://configServer:8888
#      - RABBIT_HOST=http://rabbitmq:5672
#      - RABBIT_USERNAME=root
#      - RABBIT_PASSWORD=123456
#      - HOST_NAME=configBus
  configClient:
    image: asd1245dss/cloud-config-client:latest
    networks:
      spring-cloud-overlay:
        aliases:
          - configClient
    ports:
      - "8881:8881"
    environment:
      - PROFILE=default
      - EUREKA_SERVER_LIST=http://eurekaServer1:8761/eureka/,http://eurekaServer2:8761/eureka/,http://eurekaServer3:8761/eureka/
      - CLOUD_CONFIG_SERVER=http://configServer:8888
      - RABBIT_HOST=rabbitmq
      - RABBIT_USERNAME=root
      - RABBIT_PASSWORD=123456
      - HOST_NAME=configClient

networks:
  spring-cloud-overlay:
    external:
      name: spring-cloud-overlay
