version: '3'
services:
  configClient:
    image: "asd1245dss/cloud-config-client:latest"
    networks:
      spring-cloud-overlay:
        aliases:
          - configClient
    ports:
      - "8881:8881"
    environment:
      - EUREKA_SERVER_LIST=http://eurekaServer1:8761/eureka/,http://eurekaServer2:8761/eureka/,http://eurekaServer3:8761/eureka/
      - CLOUD_CONFIG_SERVER=http://configServer:8888
      - HOST_NAME=configClient

networks:
  spring-cloud-overlay:
    external:
      name: spring-cloud-overlay
