version: '3'
services:
  eurekaServer1:
    image: "asd1245dss/cloud-eureka-server:latest"
    networks:
      spring-cloud-overlay:
        aliases:
          - eurekaServer
    ports:
      - "8761:8761"
    environment:
      - EUREKA_SERVER_LIST=http://eurekaServer2:8761/eureka/,http://eurekaServer3:8761/eureka/
      - SPRING_PROFILES_ACTIVE=cluster
      - HOST_NAME=eurekaServer1
  eurekaServer2:
    image: "asd1245dss/cloud-eureka-server:latest"
    networks:
      spring-cloud-overlay:
        aliases:
          - eurekaServer
    ports:
      - "8762:8761"
    environment:
      - EUREKA_SERVER_LIST=http://eurekaServer1:8761/eureka/,http://eurekaServer3:8761/eureka/
      - SPRING_PROFILES_ACTIVE=cluster
      - HOST_NAME=eurekaServer2
  eurekaServer3:
    image: "asd1245dss/cloud-eureka-server:latest"
    networks:
      spring-cloud-overlay:
        aliases:
          - eurekaServer
    ports:
      - "8763:8761"
    environment:
      - EUREKA_SERVER_LIST=http://eurekaServer1:8761/eureka/,http://eurekaServer2:8761/eureka/
      - SPRING_PROFILES_ACTIVE=cluster
      - HOST_NAME=eurekaServer3
  configServer:
    image: "asd1245dss/cloud-config-server:latest"
    networks:
      spring-cloud-overlay:
        aliases:
          - configServer
    ports:
      - "8888:8888"
    environment:
      - EUREKA_SERVER_LIST=http://eurekaServer1:8761/eureka/,http://eurekaServer2:8761/eureka/,http://eurekaServer3:8761/eureka/
      - SPRING_PROFILES_ACTIVE=cluster
      - HOST_NAME=configServer

networks:
  spring-cloud-overlay:
    external:
      name: spring-cloud-overlay
