version: "3"
services:
  web:
    image: asd1245dss/demo:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
        restart_policy:
          condition: on-falure
    ports:
      - "8989:8080"
    networks:
      - webnet
    volumes:
      - .:/root/docker

networks:
  webnet:
