msg: ${HOST_NAME}-${random}

server:
  port: 8881

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_LIST}
  instance:
    hostname: ${HOST_NAME}
    instance-id: ${HOST_NAME}:configClient:${server.port}
