spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/asd1245dss/demo-cloud.git
          search-paths: demo-cloud-config-repo/cloud/**
          username: ${CONFIG_REPO_USERNAME:username}
          password: ${CONFIG_REPO_PASSWORD:password}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_LIST:http://eurekaServer:8761/eureka/}
