spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/asd1245dss/demo-cloud.git
          search-paths: demo-cloud-config-repo/cloud/**
          username: ${CONFIG_REPO_USERNAME:username}
          password: ${CONFIG_REPO_PASSWORD:password}

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_LIST:http://eurekaServer:8761/eureka/}
  instance:
    hostname: ${HOST_NAME:configServer}
    instance-id: ${HOST_NAME:configServer}:${spring.application.name}:${server.port}
