spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/asd1245dss/demo-spring
          search-paths: demo-spring-cloud-config-server/src/main/resources/cloud/**

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_LIST:http://eurekaServer:8761/eureka/}
  instance:
    hostname: ${HOST_NAME:configServer}
    instance-id: ${HOST_NAME:configServer}:${spring.application.name}:${server.port}
management:
  security:
    enabled: false
