server:
  port: 8881

spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: root
    password: 123456
  cloud:
    bus:
      trace:
        enabled: true
  profiles:
    active: default

management:
  security:
    enabled: false

msg: ${spring.rabbitmq.host}
