msg: ${HOST_NAME}-${EUREKA_SERVER_LIST}

server:
  port: 8881

spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  cloud:
    bus:
      trace:
        enabled: true

management:
  security:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_LIST}
  instance:
    hostname: ${HOST_NAME}
    instance-id: ${HOST_NAME}:configClient:${server.port}
